version: "3.8"

services:
  db:
    image: postgres:16.2
    container_name: "tilichodb"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=changeme567
    networks:
    - fullstack
    volumes:
    - database_postgres:/var/lib/postgresql/data

  api: 
    build: .    # this will look for Dockerfile on same path to build image
    container_name: "RestifyCask"
    environment:
      DB_USERNAME: "postgres"
      DB_PASSWORD: "changeme567"
      DB_NAME: "postgres"
      DB_HOST: "tilichodb" #this is container name from above "db" service 
      DB_TABLE: "postgres"
      DB_PORT: "5432"
      SSL_MODE: "disable"
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - fullstack

volumes:
  database_postgres:

networks:
  fullstack:
    driver: bridge              